### PR TITLE
Move to PCL Storage

### PR DESCRIPTION
**Pull request by anaisbetts**
This PR switches Datastore to use PCL Storage's async I/O abstraction. Everything now becomes Async™ and crazy town. I'm worried that this will perform worse and be way harder to debug, and probably isn't a good idea, but I wanted to put it up regardless to get thoughts.
## TODO:
- [ ] Actually get this building
- [ ] Get the tests running + passing on both iOS and Desktop
  -[ ] Check the perf hit

### CODE REVIEW

**Comment by tberman** [comment]
So, we could either go this direction, or add Android/etc implementations of the filesystem abstraction we have.

I am fairly happy with either option, interested in @pteichman's thoughts on the subject though.

**Comment by pteichman** [comment]
Background: the abstraction we have now is sort of a half-assed port of the LevelDB Env interface ( https://code.google.com/p/leveldb/source/browse/include/leveldb/env.h?r=213a68eb68ece93a8915ef18a8eba920d5a924a4 ). It was meant to support tests rather than actual portability, but we're not using it very well in the unit tests, so I'm not at all opposed to changing it out for portability's sake.

I don't think I like how this makes all the APIs async: for the calls that hit the disk, I guess it's not all that crazy, but it's probably wrong to push MemoryTablet's search tree lookups to async, especially since (as we see here) that stuff tends to pollute an API. I'd rather keep the datastore APIs simple and make concurrency a job for the caller.

In reading about PCL Storage ( https://pclstorage.codeplex.com/workitem/9 ) it looks like at least Mono and Windows Desktop don't offer async file IO anyway? So the only benefit to PCL Storage over filling out our own interface would be on WP8, and I'm not sure how much any of us care.

@paulcbetts, what platforms are you wanting to target eventually? I think I'm more interested in filling out a full-assed Env port and providing implementations for Windows and Android, if that's all we need.

**Comment by anaisbetts** [comment]
> So the only benefit to PCL Storage over filling out our own interface would be on WP8, and I'm not sure how much any of us care.

Same, though Desktop CLR on Windows supports async I/O too if you Do It Right

> @paulcbetts, what platforms are you wanting to target eventually? I think I'm more interested in filling out a full-assed Env port and providing implementations for Windows and Android, if that's all we need.

iOS / Android / Desktop CLR at least. I think I'm on your side on this one, let's just port TheFactory.Filesystem to every platform

**Comment by tberman** [comment]
Consensus! Closing :)

**Pull request closed without merging**
